---
- name: " Configure isis on differnet plattform and import jinja files from github repo"
  hosts: routers
  connection: network_cli
  
  tasks:
    
  
    - name: " to Store differnet template from jinja "
      set_fact:
      notify: config_changed
      register: cli_result
 
    - name: " to Apply isis on differnet plattform via ssh "
      cli_config:
        config: "{{ lookup('template',isis_path) }}"

      notify: config_changed
      register: cli_result
      

  handlers:
    - name: " display changed "
      listen: config_changed
      debug:
        msg: "{{ cli_result }}"
